name: Pull Request Action
on:
  push:
    branches:
      - psd2_monitoring_report_*

jobs:
  create-pull-request:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: ${{ github.ref }}
          title: ${{ github.ref }}
          base: master
          branch: ${{ github.ref }}
